export interface GlossaryEntry {
  term: string
  definition: string
}

export function todaysTerm(): GlossaryEntry {
  const dayIndex = Math.floor(Date.now() / 86_400_000)
  return GLOSSARY[dayIndex % GLOSSARY.length]!
}

export const GLOSSARY: GlossaryEntry[] = [
  // ── Crypto Fundamentals ──
  { term: 'Bitcoin (BTC)', definition: 'The first and most well-known cryptocurrency, created in 2009. It works like digital money that no single company or government controls.' },
  { term: 'Ethereum (ETH)', definition: 'A cryptocurrency platform that lets developers build apps on top of it. Think of it as a programmable version of Bitcoin.' },
  { term: 'Blockchain', definition: 'A digital ledger that records every transaction across a network of computers. Once something is written, it cannot be changed.' },
  { term: 'Cryptocurrency', definition: 'Digital money that uses math and code to verify transactions instead of a bank or government.' },
  { term: 'Altcoin', definition: 'Any cryptocurrency other than Bitcoin. Examples include Ethereum, Solana, and XRP.' },
  { term: 'Stablecoin', definition: 'A cryptocurrency designed to keep a steady value, usually pegged to the US dollar. USDT and USDC are popular examples.' },
  { term: 'Token', definition: 'A digital asset built on top of an existing blockchain, like an app running on a phone\'s operating system.' },
  { term: 'Wallet', definition: 'Software or hardware that stores the keys you need to send and receive cryptocurrency — like a digital bank account you fully control.' },
  { term: 'Private Key', definition: 'A secret code that lets you spend your crypto. Whoever has it controls the funds, so it must be kept safe.' },
  { term: 'Public Key', definition: 'Your crypto address that others use to send you funds. It is safe to share, like an email address.' },
  { term: 'Seed Phrase', definition: 'A set of 12 or 24 words that can restore your entire wallet if you lose access. It should never be shared with anyone.' },
  { term: 'Mining', definition: 'Using powerful computers to verify transactions and add them to the blockchain. Miners are rewarded with new coins for their work.' },
  { term: 'Proof of Work (PoW)', definition: 'A system where computers compete to solve puzzles to validate transactions. Bitcoin uses this method.' },
  { term: 'Proof of Stake (PoS)', definition: 'A system where people lock up their coins to help validate transactions. The more you stake, the higher your chance of being chosen. Ethereum uses this.' },
  { term: 'Staking', definition: 'Locking up your crypto to help secure a network, earning rewards in return — similar to earning interest at a bank.' },
  { term: 'Gas Fee', definition: 'A small payment you make to process a transaction on networks like Ethereum. Fees go up when the network is busy.' },
  { term: 'Block', definition: 'A batch of transactions grouped together and added to the blockchain. A new Bitcoin block is created roughly every 10 minutes.' },
  { term: 'Block Reward', definition: 'The new coins given to a miner or validator for successfully adding a block of transactions to the chain.' },
  { term: 'Halving', definition: 'An event where the reward for mining Bitcoin is cut in half, happening roughly every four years. It makes new supply scarcer over time.' },
  { term: 'Hash Rate', definition: 'The total computing power being used to mine and secure a blockchain. A higher hash rate means a more secure network.' },
  { term: 'Node', definition: 'A computer that keeps a copy of the blockchain and helps validate transactions. Thousands of nodes keep the network honest.' },
  { term: 'Consensus', definition: 'The process by which all computers on a blockchain agree on which transactions are valid, without needing a central authority.' },
  { term: 'Fork', definition: 'When a blockchain splits into two paths. A "hard fork" creates a new coin (like Bitcoin Cash from Bitcoin), while a "soft fork" is a backward-compatible upgrade.' },
  { term: 'Smart Contract', definition: 'Code that runs on a blockchain and automatically executes when conditions are met — like a vending machine that delivers once you pay.' },
  { term: 'Decentralized Application (dApp)', definition: 'An app that runs on a blockchain instead of a company\'s servers. No single entity controls it.' },
  { term: 'DeFi', definition: 'Short for Decentralized Finance — financial services like lending, borrowing, and trading built on blockchains without traditional banks.' },
  { term: 'DEX', definition: 'A Decentralized Exchange where you trade crypto directly with others, without a middleman holding your funds.' },
  { term: 'CEX', definition: 'A Centralized Exchange like Coinbase or Binance, where a company holds your funds and matches buyers with sellers.' },
  { term: 'Liquidity', definition: 'How easily you can buy or sell an asset without moving its price much. High liquidity means smoother trades.' },
  { term: 'Liquidity Pool', definition: 'A pot of crypto funds locked in a smart contract that anyone can trade against. Providers earn fees for contributing.' },
  { term: 'Yield Farming', definition: 'Moving your crypto between DeFi platforms to earn the highest possible returns, like shopping around for the best savings rate.' },
  { term: 'AMM', definition: 'Automated Market Maker — a system that uses math formulas instead of order books to set prices on decentralized exchanges.' },
  { term: 'NFT', definition: 'Non-Fungible Token — a unique digital item on a blockchain, like a certificate of ownership for digital art or collectibles.' },
  { term: 'DAO', definition: 'Decentralized Autonomous Organization — a group governed by code and community votes instead of a traditional board of directors.' },
  { term: 'Airdrop', definition: 'Free tokens sent to wallet addresses, usually to promote a new project or reward early users.' },
  { term: 'ICO', definition: 'Initial Coin Offering — a fundraising method where a new project sells tokens to early investors, similar to a stock IPO.' },
  { term: 'Whitepaper', definition: 'A document that explains how a crypto project works, its goals, and the technology behind it.' },
  { term: 'Tokenomics', definition: 'The economic design of a token — how many exist, how they are distributed, and what incentives drive their value.' },
  { term: 'Market Cap', definition: 'The total value of a cryptocurrency, calculated by multiplying its price by the number of coins in circulation.' },
  { term: 'Circulating Supply', definition: 'The number of coins currently available for trading. Not all coins created may be in circulation.' },
  { term: 'Total Supply', definition: 'The maximum number of coins that will ever exist. Bitcoin\'s total supply is capped at 21 million.' },
  { term: 'Burn', definition: 'Permanently destroying coins to reduce supply, which can increase the value of remaining coins.' },
  { term: 'Whale', definition: 'Someone who holds a very large amount of cryptocurrency. Their trades can move the market noticeably.' },
  { term: 'HODL', definition: 'Slang for holding your crypto instead of selling, even when prices drop. Originally a typo for "hold."' },
  { term: 'FOMO', definition: 'Fear Of Missing Out — the anxiety that makes people buy an asset because everyone else is, often at the worst time.' },
  { term: 'FUD', definition: 'Fear, Uncertainty, and Doubt — negative news or rumors spread to scare people into selling.' },
  { term: 'Rug Pull', definition: 'A scam where project creators suddenly withdraw all funds and disappear, leaving investors with worthless tokens.' },
  { term: 'KYC', definition: 'Know Your Customer — identity verification that exchanges require to comply with laws and prevent fraud.' },
  { term: 'AML', definition: 'Anti-Money Laundering — rules that crypto platforms must follow to prevent illegal money transfers.' },
  { term: 'Cold Storage', definition: 'Keeping your crypto offline on a hardware device, completely safe from online hackers.' },
  { term: 'Hot Wallet', definition: 'A wallet connected to the internet for easy access. Convenient but more vulnerable to attacks than cold storage.' },

  // ── Trading Terms ──
  { term: 'Bull Market', definition: 'A period when prices are rising or expected to rise. Optimism and buying dominate the market.' },
  { term: 'Bear Market', definition: 'A period when prices are falling or expected to fall, usually defined as a drop of 20% or more from recent highs.' },
  { term: 'Support Level', definition: 'A price where an asset tends to stop falling because buyers step in. Think of it as a floor.' },
  { term: 'Resistance Level', definition: 'A price where an asset tends to stop rising because sellers take profits. Think of it as a ceiling.' },
  { term: 'Breakout', definition: 'When a price moves above resistance or below support with strong momentum, often starting a new trend.' },
  { term: 'Moving Average', definition: 'The average price over a set number of days, smoothing out daily noise to reveal the overall trend.' },
  { term: '200-Day Moving Average', definition: 'A long-term trend indicator. When the price is above it, the trend is generally considered positive.' },
  { term: 'Volume', definition: 'The total amount of an asset traded in a given period. High volume confirms that a price move has conviction.' },
  { term: 'Volatility', definition: 'How much and how quickly a price changes. Crypto is known for high volatility compared to stocks.' },
  { term: 'Candlestick', definition: 'A chart bar showing the open, close, high, and low prices for a time period. Green means the price went up, red means it went down.' },
  { term: 'Trend', definition: 'The general direction of a price over time — up (bullish), down (bearish), or sideways (ranging).' },
  { term: 'Correction', definition: 'A temporary price decline of 10–20% during an overall uptrend. It is considered normal and healthy.' },
  { term: 'Rally', definition: 'A sustained increase in price, often driven by positive news or strong buying momentum.' },
  { term: 'Dip', definition: 'A short-term price drop. "Buying the dip" means purchasing during a temporary decline.' },
  { term: 'All-Time High (ATH)', definition: 'The highest price an asset has ever reached. Breaking the ATH often triggers excitement and media attention.' },
  { term: 'All-Time Low (ATL)', definition: 'The lowest price an asset has ever reached.' },
  { term: 'Limit Order', definition: 'An order to buy or sell at a specific price or better. It only executes when the market reaches your price.' },
  { term: 'Market Order', definition: 'An order to buy or sell immediately at the current best available price.' },
  { term: 'Stop-Loss', definition: 'An automatic sell order that triggers if the price drops to a set level, limiting your losses.' },
  { term: 'Take-Profit', definition: 'An automatic sell order that triggers when the price reaches your target, locking in gains.' },
  { term: 'Leverage', definition: 'Borrowing money to trade a larger position than your balance allows. It amplifies both gains and losses.' },
  { term: 'Margin', definition: 'The amount of your own money required to open a leveraged position. If your losses eat into it, you may face a margin call.' },
  { term: 'Margin Call', definition: 'A demand to add more funds to your account when a leveraged trade moves against you. Failing to do so can lead to forced selling.' },
  { term: 'Liquidation', definition: 'When your leveraged position is automatically closed because your losses exceeded your margin.' },
  { term: 'Short Selling', definition: 'Betting that a price will fall. You borrow and sell an asset, hoping to buy it back cheaper later.' },
  { term: 'Going Long', definition: 'Buying an asset because you expect its price to rise.' },
  { term: 'Order Book', definition: 'A list of all open buy and sell orders for an asset, showing what prices traders are willing to pay.' },
  { term: 'Bid', definition: 'The highest price a buyer is currently willing to pay for an asset.' },
  { term: 'Ask', definition: 'The lowest price a seller is currently willing to accept for an asset.' },
  { term: 'Spread', definition: 'The difference between the bid and ask prices. A smaller spread means better liquidity.' },
  { term: 'Slippage', definition: 'The difference between the price you expected and the price you actually got, common in fast-moving or thin markets.' },
  { term: 'Dollar-Cost Averaging (DCA)', definition: 'Investing a fixed amount at regular intervals regardless of price, smoothing out the highs and lows over time.' },
  { term: 'Portfolio', definition: 'The collection of all your investments — stocks, crypto, bonds, etc. — considered together.' },
  { term: 'Diversification', definition: 'Spreading your investments across different assets to reduce risk. "Don\'t put all your eggs in one basket."' },
  { term: 'Risk/Reward Ratio', definition: 'A comparison of how much you could lose versus how much you could gain on a trade. A 1:3 ratio means you risk $1 to potentially make $3.' },
  { term: 'ROI', definition: 'Return on Investment — the percentage gain or loss relative to how much you invested.' },
  { term: 'Unrealized Gain', definition: 'Profit on paper — your holding has grown in value but you have not sold yet.' },
  { term: 'Realized Gain', definition: 'Profit that you have actually locked in by selling an asset at a higher price than you paid.' },
  { term: 'Paper Hands', definition: 'Slang for someone who sells at the first sign of trouble, unable to hold through volatility.' },
  { term: 'Diamond Hands', definition: 'Slang for someone who holds their position through extreme volatility, refusing to sell.' },
  { term: 'Pump and Dump', definition: 'A scheme where a group artificially inflates the price of an asset and then sells it, leaving late buyers with losses.' },
  { term: 'Dead Cat Bounce', definition: 'A brief price recovery during a larger decline. It looks like a rebound but the downtrend continues.' },

  // ── Technical Analysis ──
  { term: 'Technical Analysis', definition: 'Studying price charts and patterns to predict future price movements, based on the idea that history tends to repeat.' },
  { term: 'Fundamental Analysis', definition: 'Evaluating an asset by looking at its underlying value — the team, technology, revenue, or real-world use.' },
  { term: 'RSI (Relative Strength Index)', definition: 'A 0-to-100 score showing whether an asset is overbought (above 70) or oversold (below 30) based on recent price changes.' },
  { term: 'MACD', definition: 'Moving Average Convergence Divergence — a tool that shows when a trend may be gaining or losing strength by comparing two moving averages.' },
  { term: 'Bollinger Bands', definition: 'Lines plotted above and below a moving average that widen during volatile periods and narrow during calm ones.' },
  { term: 'Fibonacci Retracement', definition: 'A tool that uses mathematical ratios to identify potential support and resistance levels during a pullback.' },
  { term: 'Golden Cross', definition: 'When a short-term moving average crosses above a long-term one, often seen as a bullish signal.' },
  { term: 'Death Cross', definition: 'When a short-term moving average crosses below a long-term one, often seen as a bearish signal.' },
  { term: 'Divergence', definition: 'When the price moves in one direction but an indicator moves in the opposite, hinting at a potential trend reversal.' },
  { term: 'Overbought', definition: 'When an asset has risen too fast and may be due for a pullback. Indicators like RSI help spot this.' },
  { term: 'Oversold', definition: 'When an asset has fallen too fast and may be due for a bounce. It does not guarantee a reversal.' },
  { term: 'Chart Pattern', definition: 'Recognizable shapes on price charts — like triangles, flags, and head-and-shoulders — that traders use to predict moves.' },
  { term: 'Head and Shoulders', definition: 'A chart pattern with three peaks where the middle one is tallest, often signaling a trend reversal.' },
  { term: 'Double Top', definition: 'A chart pattern where the price hits a high twice and fails to break through, suggesting a downturn.' },
  { term: 'Double Bottom', definition: 'A chart pattern where the price hits a low twice and bounces, suggesting an upturn.' },
  { term: 'Ascending Triangle', definition: 'A bullish chart pattern with a flat top and rising lower trendline, suggesting buyers are gradually pushing higher.' },
  { term: 'Flag Pattern', definition: 'A brief consolidation after a strong move that looks like a small rectangle, usually followed by a continuation of the trend.' },
  { term: 'Wedge', definition: 'A chart pattern where price action narrows between converging trendlines, often preceding a breakout.' },
  { term: 'Cup and Handle', definition: 'A bullish chart pattern shaped like a tea cup, with a rounded bottom followed by a smaller dip before the price breaks out.' },
  { term: 'Trendline', definition: 'A straight line drawn along highs or lows on a chart to show the direction of the price movement.' },
  { term: 'Time Frame', definition: 'The period each candlestick represents — 1 minute, 1 hour, 1 day, etc. Longer time frames show bigger-picture trends.' },

  // ── Macro Economics ──
  { term: 'Inflation', definition: 'When prices of goods and services rise over time, reducing the purchasing power of money.' },
  { term: 'Deflation', definition: 'When prices of goods and services fall over time. It sounds good but can signal a struggling economy.' },
  { term: 'Interest Rate', definition: 'The cost of borrowing money, set by central banks. Higher rates make borrowing expensive, slowing economic activity.' },
  { term: 'Federal Reserve (Fed)', definition: 'The central bank of the United States. Its decisions on interest rates and money supply affect global markets.' },
  { term: 'Quantitative Easing (QE)', definition: 'When a central bank creates new money to buy bonds, injecting cash into the economy to stimulate growth.' },
  { term: 'Quantitative Tightening (QT)', definition: 'The opposite of QE — the central bank reduces its holdings, pulling money out of the economy.' },
  { term: 'CPI (Consumer Price Index)', definition: 'A measure of inflation that tracks how much everyday goods and services cost over time.' },
  { term: 'GDP (Gross Domestic Product)', definition: 'The total value of all goods and services produced in a country, used to measure economic health.' },
  { term: 'Recession', definition: 'A significant decline in economic activity lasting months. Commonly defined as two consecutive quarters of falling GDP.' },
  { term: 'Yield', definition: 'The income earned from an investment, usually expressed as a percentage. Bond yields rise when bond prices fall.' },
  { term: 'Yield Curve', definition: 'A graph showing interest rates on government bonds of different lengths. An inverted curve (short rates above long) has historically preceded recessions.' },
  { term: 'Basis Points', definition: 'A unit of measurement for interest rates. 100 basis points equals 1 percentage point.' },
  { term: 'Treasury Bond', definition: 'A loan you make to the US government. Considered one of the safest investments, with returns based on the interest rate.' },
  { term: 'Monetary Policy', definition: 'How a central bank manages the money supply and interest rates to control inflation and support the economy.' },
  { term: 'Fiscal Policy', definition: 'How a government uses spending and taxes to influence the economy. Stimulus checks are a form of fiscal policy.' },
  { term: 'Risk-On', definition: 'A market mood where investors are confident and willing to buy riskier assets like stocks and crypto.' },
  { term: 'Risk-Off', definition: 'A market mood where investors are cautious and move money into safer assets like bonds and gold.' },
  { term: 'Safe Haven', definition: 'An asset expected to hold or gain value during turbulent times — gold and US Treasury bonds are classic examples.' },
  { term: 'Correlation', definition: 'How closely two assets move together. A high correlation means they tend to rise and fall at the same time.' },
  { term: 'Decoupling', definition: 'When an asset that usually moves with another breaks away and starts trending independently.' },
  { term: 'Soft Landing', definition: 'When a central bank slows the economy enough to tame inflation without causing a recession.' },
  { term: 'Hard Landing', definition: 'When efforts to cool an overheating economy trigger a recession.' },
  { term: 'Taper', definition: 'When a central bank gradually reduces its bond-buying program, signaling a shift toward tighter policy.' },
  { term: 'Dovish', definition: 'A stance favoring lower interest rates and more stimulus to support economic growth.' },
  { term: 'Hawkish', definition: 'A stance favoring higher interest rates and tighter policy to fight inflation.' },

  // ── Market Structure ──
  { term: 'Stock', definition: 'A share of ownership in a company. When the company does well, the stock price tends to rise.' },
  { term: 'Bond', definition: 'A loan to a government or company that pays you back with interest over time. Generally safer than stocks.' },
  { term: 'Commodity', definition: 'A raw material like gold, oil, or wheat that is traded on exchanges.' },
  { term: 'Index', definition: 'A basket of assets tracked together to represent a market. The S&P 500 tracks 500 large US companies.' },
  { term: 'S&P 500', definition: 'An index of 500 of the largest publicly traded companies in the US, widely used as a measure of the overall stock market.' },
  { term: 'Dow Jones Industrial Average', definition: 'An index of 30 major US companies. One of the oldest and most-watched stock market indicators.' },
  { term: 'NASDAQ', definition: 'A stock exchange heavy on technology companies. The NASDAQ Composite index tracks over 3,000 stocks listed there.' },
  { term: 'ETF', definition: 'Exchange-Traded Fund — a basket of assets you can buy as a single trade, like a pre-made investment mix.' },
  { term: 'Spot Price', definition: 'The current market price for immediate delivery of an asset.' },
  { term: 'Futures', definition: 'Contracts to buy or sell an asset at a predetermined price on a specific future date.' },
  { term: 'Options', definition: 'Contracts that give you the right, but not the obligation, to buy or sell an asset at a set price before a deadline.' },
  { term: 'Derivatives', definition: 'Financial instruments whose value comes from an underlying asset — futures and options are common examples.' },
  { term: 'IPO', definition: 'Initial Public Offering — when a private company first sells shares to the public on a stock exchange.' },
  { term: 'Market Maker', definition: 'A firm that provides liquidity by always being ready to buy and sell, earning the spread as profit.' },
  { term: 'Arbitrage', definition: 'Profiting from price differences of the same asset on different markets, buying low on one and selling high on another.' },
  { term: 'OTC (Over-the-Counter)', definition: 'Trading done directly between two parties without going through a public exchange, common for large deals.' },
  { term: 'Penny Stock', definition: 'A very low-priced stock, usually under $5. High risk and often highly volatile.' },
  { term: 'Blue Chip', definition: 'A large, well-established, financially stable company. Blue-chip stocks are considered reliable investments.' },
  { term: 'Dividend', definition: 'A portion of a company\'s profits paid to shareholders, usually quarterly.' },
  { term: 'Market Hours', definition: 'The times when a stock exchange is open for trading. US markets operate 9:30 AM to 4:00 PM Eastern.' },
  { term: 'After-Hours Trading', definition: 'Buying and selling that occurs outside regular market hours. Volume is lower and prices can be more volatile.' },
  { term: 'Circuit Breaker', definition: 'Automatic trading halts triggered when a market drops by a certain percentage, designed to prevent panic selling.' },
  { term: 'Market Capitalization', definition: 'The total value of all shares or coins, calculated as price multiplied by quantity outstanding.' },
  { term: 'Float', definition: 'The number of shares or tokens available for public trading, excluding those locked by insiders.' },

  // ── Crypto-specific Advanced ──
  { term: 'Layer 1', definition: 'The base blockchain itself — Bitcoin, Ethereum, and Solana are all Layer 1 networks.' },
  { term: 'Layer 2', definition: 'A network built on top of a Layer 1 to make it faster and cheaper. Lightning Network and Arbitrum are examples.' },
  { term: 'Rollup', definition: 'A Layer 2 technology that bundles many transactions together and submits them to the main chain as one, cutting costs.' },
  { term: 'Sidechain', definition: 'A separate blockchain connected to a main chain, allowing assets to move between them for different features or speeds.' },
  { term: 'Bridge', definition: 'A tool that moves tokens between different blockchains. Bridges can be risky — several have been hacked.' },
  { term: 'Oracle', definition: 'A service that feeds real-world data (like prices or weather) into smart contracts, since blockchains cannot access outside information on their own.' },
  { term: 'TVL (Total Value Locked)', definition: 'The total amount of crypto deposited in a DeFi protocol. It measures how much trust users place in the platform.' },
  { term: 'Impermanent Loss', definition: 'A temporary loss that liquidity providers may experience when the price of their deposited tokens changes compared to just holding them.' },
  { term: 'Flash Loan', definition: 'A loan that is borrowed and repaid within a single blockchain transaction — no collateral needed, but all in one instant.' },
  { term: 'Wrapped Token', definition: 'A token that represents another asset on a different blockchain. WBTC is Bitcoin wrapped for use on Ethereum.' },
  { term: 'Gas Limit', definition: 'The maximum amount of computational work you are willing to pay for in a blockchain transaction.' },
  { term: 'Gwei', definition: 'A tiny unit of Ether used to measure gas fees on Ethereum. One Gwei is one-billionth of an ETH.' },
  { term: 'ERC-20', definition: 'The standard for creating tokens on Ethereum. Most tokens you see on decentralized exchanges follow this standard.' },
  { term: 'ERC-721', definition: 'The Ethereum standard for non-fungible tokens (NFTs), giving each token a unique identity.' },
  { term: 'Mempool', definition: 'The waiting room for unconfirmed transactions before they are included in a block.' },
  { term: 'MEV', definition: 'Maximal Extractable Value — profit that validators can earn by reordering or inserting transactions in a block.' },
  { term: 'Slashing', definition: 'A penalty where a validator loses part of their staked coins for misbehaving or going offline.' },
  { term: 'Validator', definition: 'A participant who locks up coins and runs software to verify transactions on a Proof of Stake network.' },
  { term: 'Epoch', definition: 'A set period of time in a blockchain protocol during which certain events occur, like validator selection.' },
  { term: 'Governance Token', definition: 'A token that gives holders voting rights on how a project is run — its rules, upgrades, and treasury.' },
  { term: 'Testnet', definition: 'A practice version of a blockchain used by developers to test changes without risking real money.' },
  { term: 'Mainnet', definition: 'The live, production version of a blockchain where real transactions happen.' },
  { term: 'Hard Cap', definition: 'The absolute maximum supply of a token that will ever exist. Bitcoin\'s hard cap is 21 million.' },
  { term: 'Soft Cap', definition: 'The minimum amount a project aims to raise in a fundraising round to proceed with development.' },
  { term: 'Vesting', definition: 'A schedule that gradually releases tokens to team members or investors over time, preventing instant sell-offs.' },
  { term: 'Whale Watching', definition: 'Tracking the activity of large crypto holders to anticipate potential market-moving trades.' },
  { term: 'On-Chain', definition: 'Activity recorded directly on the blockchain — transactions, smart contract calls, and token transfers.' },
  { term: 'Off-Chain', definition: 'Activity that happens outside the blockchain, like trades on a centralized exchange\'s internal ledger.' },
  { term: 'Txn Hash', definition: 'A unique ID for a blockchain transaction that lets anyone verify its details on a block explorer.' },

  // ── Risk & Psychology ──
  { term: 'Risk Tolerance', definition: 'How much loss you can handle emotionally and financially before selling. Knowing yours helps you choose the right investments.' },
  { term: 'Confirmation Bias', definition: 'The tendency to seek out information that supports what you already believe and ignore what contradicts it.' },
  { term: 'Herd Mentality', definition: 'Following what everyone else is doing instead of making independent decisions — a common trap in investing.' },
  { term: 'Sunk Cost Fallacy', definition: 'Holding a losing investment because of how much you have already put in, rather than evaluating its future potential.' },
  { term: 'Recency Bias', definition: 'Giving too much weight to recent events when making decisions, like assuming a rally will continue just because it has been going on.' },
  { term: 'Anchoring', definition: 'Fixating on a specific number — like the price you bought at — and letting it distort your judgment about selling.' },
  { term: 'Loss Aversion', definition: 'The human tendency to feel the pain of a loss more strongly than the pleasure of an equal gain.' },
  { term: 'Black Swan', definition: 'An extremely rare and unpredictable event with massive consequences — like a pandemic crashing global markets.' },
  { term: 'Capitulation', definition: 'When investors give up hope and sell their positions at a loss, often marking the bottom of a downturn.' },
  { term: 'Accumulation', definition: 'A phase where smart money quietly buys an asset at low prices before the next big move up.' },
  { term: 'Distribution', definition: 'A phase where large holders gradually sell their positions to smaller buyers, often before a downturn.' },

  // ── Currency & Forex ──
  { term: 'Forex', definition: 'The foreign exchange market where currencies are traded. It is the largest financial market in the world.' },
  { term: 'Currency Pair', definition: 'Two currencies quoted against each other, like EUR/USD. The first is the base, the second is the quote.' },
  { term: 'Exchange Rate', definition: 'The price of one currency in terms of another. It fluctuates based on supply, demand, and economic conditions.' },
  { term: 'Dollar Index (DXY)', definition: 'A measure of the US dollar\'s value against a basket of six major currencies. A rising DXY can pressure crypto prices.' },
  { term: 'Fiat Currency', definition: 'Government-issued money like the US dollar or euro that is not backed by a physical commodity.' },
  { term: 'Peg', definition: 'When one asset\'s value is fixed to another — like a stablecoin pegged 1:1 to the US dollar.' },

  // ── Energy & Commodities ──
  { term: 'Crude Oil', definition: 'Unrefined petroleum extracted from the ground, traded globally and priced per barrel. It powers transportation and industry.' },
  { term: 'Brent Crude', definition: 'The international benchmark for oil prices, named after a North Sea oil field.' },
  { term: 'WTI (West Texas Intermediate)', definition: 'The US benchmark for oil prices, used for oil delivered at Cushing, Oklahoma.' },
  { term: 'OPEC', definition: 'Organization of the Petroleum Exporting Countries — a group that coordinates oil production to influence prices.' },
  { term: 'Gold', definition: 'A precious metal that has served as money and a store of value for thousands of years. Often called a safe-haven asset.' },
  { term: 'Silver', definition: 'A precious metal used in both industry and as an investment. It tends to be more volatile than gold.' },
  { term: 'Barrel', definition: 'The standard unit for measuring oil, equal to 42 US gallons or about 159 liters.' },
  { term: 'Spot vs Futures', definition: 'Spot is the current market price for immediate delivery; futures is the agreed price for delivery at a later date.' },

  // ── News & Sentiment ──
  { term: 'Fear & Greed Index', definition: 'A score from 0 to 100 measuring market emotion. Low scores mean fear (people are scared), high scores mean greed (people are excited).' },
  { term: 'Sentiment Analysis', definition: 'Gauging the overall mood of investors — bullish or bearish — from news, social media, and market data.' },
  { term: 'Headline Risk', definition: 'The possibility that a news story will suddenly move an asset\'s price, regardless of fundamentals.' },
  { term: 'Catalyst', definition: 'An event or piece of news that triggers a significant price move — like a regulatory decision or earnings report.' },
  { term: 'Priced In', definition: 'When the market has already adjusted for expected news, so the actual announcement has little effect.' },
  { term: 'Buy the Rumor, Sell the News', definition: 'A strategy where traders buy in anticipation of good news and sell when it is officially announced.' },
  { term: 'Market Sentiment', definition: 'The overall feeling among investors about where the market is headed — optimistic (bullish) or pessimistic (bearish).' },

  // ── Blockchain Concepts ──
  { term: 'Decentralization', definition: 'Distributing control across many participants instead of a single authority, making the system harder to censor or shut down.' },
  { term: 'Immutability', definition: 'The property that once data is recorded on a blockchain, it cannot be altered or deleted.' },
  { term: 'Permissionless', definition: 'Anyone can participate — no approval needed to send transactions, run a node, or build an application.' },
  { term: 'Trustless', definition: 'A system where you do not need to trust any single party because the rules are enforced by code and math.' },
  { term: 'Interoperability', definition: 'The ability of different blockchains to communicate and share data with each other.' },
  { term: 'Scalability', definition: 'How well a blockchain handles increasing numbers of transactions. It is one of the biggest challenges in crypto.' },
  { term: 'Throughput', definition: 'The number of transactions a blockchain can process per second. Higher throughput means faster performance.' },
  { term: 'Finality', definition: 'The point at which a transaction is permanently confirmed and cannot be reversed.' },
  { term: 'Sharding', definition: 'Splitting a blockchain into smaller pieces (shards) that process transactions in parallel, improving speed.' },
  { term: 'Merkle Tree', definition: 'A data structure that efficiently verifies the integrity of large datasets using hashes, widely used in blockchains.' },

  // ── Personal Finance ──
  { term: 'Emergency Fund', definition: 'Money set aside for unexpected expenses — typically 3 to 6 months of living costs — kept in a liquid, safe account.' },
  { term: 'Compound Interest', definition: 'Earning interest on your interest. Over time, this snowball effect can grow your money significantly.' },
  { term: 'APY', definition: 'Annual Percentage Yield — the total return you earn in a year including compound interest.' },
  { term: 'APR', definition: 'Annual Percentage Rate — the yearly interest rate without accounting for compounding.' },
  { term: 'Inflation Hedge', definition: 'An asset that holds or increases its value when inflation rises, protecting your purchasing power. Gold and Bitcoin are often cited.' },
  { term: 'Dollar Depreciation', definition: 'When the US dollar loses value relative to other currencies or goods, making imports and foreign travel more expensive.' },
  { term: 'Asset Allocation', definition: 'How you divide your money among different types of investments — stocks, bonds, crypto, cash — to manage risk.' },
  { term: 'Rebalancing', definition: 'Adjusting your portfolio back to your target allocation after market moves shift the proportions.' },
  { term: 'Tax-Loss Harvesting', definition: 'Selling losing investments to offset gains and reduce your tax bill, then reinvesting in something similar.' },
  { term: 'Capital Gains Tax', definition: 'A tax on the profit you make from selling an investment. Rates differ depending on how long you held the asset.' },

  // ── Security ──
  { term: 'Phishing', definition: 'A scam where attackers pretend to be a trusted entity to trick you into revealing passwords or private keys.' },
  { term: 'Two-Factor Authentication (2FA)', definition: 'An extra security step requiring both your password and a code from your phone to log in.' },
  { term: 'Multisig', definition: 'A wallet that requires multiple people to approve a transaction before it goes through, adding a layer of security.' },
  { term: 'Social Engineering', definition: 'Manipulating people into giving up sensitive information, often through deception rather than technical hacking.' },
  { term: '51% Attack', definition: 'When a group controls more than half of a blockchain\'s computing power, allowing them to manipulate transactions.' },
  { term: 'Audit', definition: 'A professional review of a smart contract\'s code to find bugs and security vulnerabilities before launch.' },
  { term: 'Bug Bounty', definition: 'A reward offered to anyone who finds and reports a security flaw in a project, rather than exploiting it.' },

  // ── Emerging Concepts ──
  { term: 'Web3', definition: 'The vision of a more decentralized internet where users own their data and digital assets instead of big tech companies.' },
  { term: 'Metaverse', definition: 'A collective virtual world where people can interact, trade, and create using digital avatars and assets.' },
  { term: 'GameFi', definition: 'Games that use crypto and NFTs to let players earn real money while playing.' },
  { term: 'SocialFi', definition: 'Social media platforms built on blockchains where creators own their content and can monetize directly.' },
  { term: 'RWA (Real World Assets)', definition: 'Physical assets like real estate or bonds that are tokenized and brought onto a blockchain for easier trading.' },
  { term: 'Zero-Knowledge Proof', definition: 'A way to prove you know something without revealing the actual information — used for privacy and scaling in crypto.' },
  { term: 'Account Abstraction', definition: 'A blockchain upgrade that makes crypto wallets work more like regular apps, with features like password recovery.' },
  { term: 'Restaking', definition: 'Using already-staked crypto to secure additional networks, earning extra rewards from multiple protocols at once.' },
  { term: 'Modular Blockchain', definition: 'A design where different parts of a blockchain (execution, data, consensus) are handled by specialized layers.' },
  { term: 'Data Availability', definition: 'Ensuring that all the data needed to verify blockchain transactions is accessible to everyone, not hidden.' },

  // ── DeFi Specifics ──
  { term: 'Lending Protocol', definition: 'A DeFi platform where you can lend your crypto to earn interest or borrow against your holdings.' },
  { term: 'Collateral', definition: 'Assets you lock up as a guarantee when borrowing. If you cannot repay, the collateral is taken.' },
  { term: 'Overcollateralized', definition: 'When you must deposit more value than you borrow — common in DeFi to protect against price drops.' },
  { term: 'Liquidation Ratio', definition: 'The point at which your collateral value falls too low relative to your loan, triggering automatic selling.' },
  { term: 'Staking Rewards', definition: 'The crypto you earn for staking your tokens to help secure a network, similar to interest on a savings account.' },
  { term: 'LP Token', definition: 'A receipt token given to liquidity providers, representing their share of a pool and redeemable for the underlying assets.' },
  { term: 'Synthetic Asset', definition: 'A token that mirrors the price of another asset — like a synthetic version of gold or Tesla stock on a blockchain.' },
  { term: 'Perpetual Swap', definition: 'A futures contract with no expiration date, widely used in crypto trading for leveraged positions.' },
  { term: 'Funding Rate', definition: 'A periodic payment between long and short traders in perpetual swaps that keeps the contract price close to the spot price.' },

  // ── Regulation ──
  { term: 'SEC', definition: 'The US Securities and Exchange Commission — the agency that regulates stocks, bonds, and some crypto offerings.' },
  { term: 'CFTC', definition: 'The Commodity Futures Trading Commission — the US agency that oversees futures and some crypto derivatives.' },
  { term: 'MiCA', definition: 'Markets in Crypto-Assets — the European Union\'s regulatory framework for cryptocurrencies and stablecoins.' },
  { term: 'Howey Test', definition: 'A US legal test to determine whether something is a security. If it involves investing money in a common enterprise expecting profit from others\' efforts, it likely is.' },
  { term: 'Accredited Investor', definition: 'Someone who meets specific income or net worth thresholds, qualifying them for certain restricted investment opportunities.' },
  { term: 'Custody', definition: 'Holding assets on behalf of someone else. In crypto, custodial services hold your private keys for you.' },
  { term: 'Self-Custody', definition: 'Holding your own private keys so no one else has control over your crypto — "not your keys, not your coins."' },

  // ── Market Metrics ──
  { term: 'P/E Ratio', definition: 'Price-to-Earnings Ratio — a measure of how expensive a stock is relative to its profits. Higher can mean overvalued or high growth expected.' },
  { term: 'Market Dominance', definition: 'The percentage of total crypto market cap held by a single coin. Bitcoin dominance above 50% means Bitcoin is leading the market.' },
  { term: 'Volume Profile', definition: 'A chart tool showing how much trading occurred at each price level, revealing where the most activity has happened.' },
  { term: 'Open Interest', definition: 'The total number of outstanding futures or options contracts that have not been settled.' },
  { term: 'Funding Heatmap', definition: 'A visualization showing whether perpetual swap traders are predominantly long or short, based on funding rates.' },
  { term: 'NVT Ratio', definition: 'Network Value to Transactions — a crypto metric comparing market cap to transaction volume, similar to P/E for stocks.' },
  { term: 'MVRV Ratio', definition: 'Market Value to Realized Value — compares the current market cap to the average purchase price of all coins, helping gauge if the market is over or undervalued.' },
  { term: 'Stock-to-Flow', definition: 'A model that compares an asset\'s current supply to the rate of new production. Applied to Bitcoin, it suggests scarcity drives value.' },
  { term: 'Sharpe Ratio', definition: 'A measure of risk-adjusted return — how much extra return you get per unit of risk taken.' },
  { term: 'Beta', definition: 'A measure of how much an asset moves relative to a benchmark. A beta above 1 means more volatile than the market.' },
  { term: 'Alpha', definition: 'Returns above the market benchmark. An investment that beats the S&P 500 is said to generate alpha.' },
  { term: 'Max Drawdown', definition: 'The largest peak-to-trough decline in value. It shows the worst-case loss an investment experienced.' },

  // ── Stablecoin Mechanics ──
  { term: 'USDT (Tether)', definition: 'The most widely used stablecoin, designed to maintain a 1:1 value with the US dollar through reserves.' },
  { term: 'USDC', definition: 'A stablecoin backed by US dollar reserves and regularly audited, created by Circle and Coinbase.' },
  { term: 'DAI', definition: 'A decentralized stablecoin maintained by the MakerDAO protocol, backed by crypto collateral rather than bank deposits.' },
  { term: 'Depeg', definition: 'When a stablecoin loses its 1:1 value with its target currency, causing panic and potential losses.' },
  { term: 'Algorithmic Stablecoin', definition: 'A stablecoin that uses code and incentive mechanisms instead of reserves to maintain its peg. Some have failed spectacularly.' },

  // ── Mining & Energy ──
  { term: 'ASIC', definition: 'Application-Specific Integrated Circuit — specialized hardware designed solely for cryptocurrency mining.' },
  { term: 'GPU Mining', definition: 'Using graphics cards to mine cryptocurrency. Less specialized than ASICs but more versatile.' },
  { term: 'Mining Pool', definition: 'A group of miners who combine their computing power and split the rewards, providing more consistent income.' },
  { term: 'Difficulty Adjustment', definition: 'An automatic change in how hard it is to mine a block, ensuring blocks are produced at a consistent rate.' },
  { term: 'Energy Consumption', definition: 'The electricity used by a blockchain network. Bitcoin mining uses significant energy, sparking debates about sustainability.' },

  // ── Order Types ──
  { term: 'Trailing Stop', definition: 'A stop-loss that automatically moves up as the price rises, locking in profits while protecting against drops.' },
  { term: 'OCO Order', definition: 'One-Cancels-the-Other — two linked orders where executing one automatically cancels the other.' },
  { term: 'Fill or Kill', definition: 'An order that must be executed immediately and completely, or it is cancelled entirely.' },
  { term: 'Good Till Cancelled (GTC)', definition: 'An order that remains active until it is either filled or you manually cancel it.' },

  // ── Advanced Crypto ──
  { term: 'Atomic Swap', definition: 'A way to trade cryptocurrencies across different blockchains without needing an exchange or intermediary.' },
  { term: 'State Channel', definition: 'A Layer 2 solution where parties transact off-chain and only settle the final result on-chain, reducing fees.' },
  { term: 'Plasma', definition: 'An early Ethereum scaling solution that creates smaller child chains anchored to the main chain.' },
  { term: 'Optimistic Rollup', definition: 'A Layer 2 that assumes transactions are valid by default and only runs fraud proofs if challenged.' },
  { term: 'ZK-Rollup', definition: 'A Layer 2 that uses zero-knowledge proofs to verify transactions, offering strong security and scalability.' },
  { term: 'Blob', definition: 'A large chunk of data attached to Ethereum transactions specifically for Layer 2 data availability, reducing costs.' },
  { term: 'EIP', definition: 'Ethereum Improvement Proposal — a formal suggestion for changes to the Ethereum network, debated and voted on by the community.' },
  { term: 'BIP', definition: 'Bitcoin Improvement Proposal — a formal suggestion for changes to the Bitcoin protocol.' },
  { term: 'Taproot', definition: 'A Bitcoin upgrade that improves privacy and efficiency by making complex transactions look like simple ones.' },

  // ── Additional Finance ──
  { term: 'Hedge', definition: 'An investment made to reduce risk from another position — like buying gold to offset potential stock losses.' },
  { term: 'Short Squeeze', definition: 'When a heavily shorted asset rises sharply, forcing short sellers to buy back and pushing the price even higher.' },
  { term: 'Gamma Squeeze', definition: 'When market makers who sold options are forced to buy the underlying asset to hedge, amplifying a price spike.' },
  { term: 'Dark Pool', definition: 'A private exchange where large trades happen anonymously, hidden from the public order book until after execution.' },
  { term: 'Flash Crash', definition: 'A sudden, dramatic drop in price that recovers almost as quickly, often caused by algorithmic trading or a cascade of stop-losses.' },
  { term: 'Liquidity Crisis', definition: 'When markets seize up and it becomes very hard to buy or sell without massive price impact.' },
  { term: 'Contagion', definition: 'When financial trouble at one institution or market spreads to others, like dominoes falling.' },
  { term: 'Deleveraging', definition: 'When traders or institutions reduce their borrowed positions, often under pressure, leading to forced selling.' },
  { term: 'Window Dressing', definition: 'When fund managers rearrange holdings before a reporting period to make the portfolio look better on paper.' },
  { term: 'Pain Trade', definition: 'A market move that hurts the most traders — often the move nobody expects.' },
  { term: 'Mean Reversion', definition: 'The idea that prices tend to return to their long-term average over time, after swinging too far in either direction.' },
  { term: 'Momentum Trading', definition: 'A strategy that buys assets rising in price and sells those falling, betting that trends continue.' },
  { term: 'Swing Trading', definition: 'Holding a position for days to weeks, aiming to profit from expected short-term price swings.' },
  { term: 'Scalping', definition: 'Making many small, quick trades to capture tiny price movements, often within minutes or seconds.' },
  { term: 'Position Sizing', definition: 'Deciding how much of your portfolio to risk on a single trade, based on your strategy and risk tolerance.' },
  { term: 'Bag Holder', definition: 'Someone stuck holding a losing investment that has dropped significantly, often because they did not sell in time.' },
  { term: 'Exit Strategy', definition: 'A planned approach for selling an investment — deciding in advance when you will take profits or cut losses.' },
  { term: 'Averaging Down', definition: 'Buying more of an asset after its price drops, lowering your average cost — risky if the decline continues.' },
  { term: 'Breakeven', definition: 'The price at which you neither gain nor lose on an investment.' },
  { term: 'Annualized Return', definition: 'The average yearly return of an investment over a period, making it easier to compare investments of different durations.' },
  { term: 'Benchmark', definition: 'A standard against which investment performance is measured — the S&P 500 is a common benchmark for US stocks.' },

  // ── Geopolitics & Markets ──
  { term: 'Sanctions', definition: 'Government-imposed restrictions on trade or financial dealings with specific countries, entities, or individuals.' },
  { term: 'Embargo', definition: 'A ban on trading with a particular country, often used as a political tool.' },
  { term: 'Trade War', definition: 'When countries impose tariffs and trade barriers on each other, disrupting global supply chains and markets.' },
  { term: 'Tariff', definition: 'A tax on imported goods, designed to protect domestic industries or as a bargaining tool in trade disputes.' },
  { term: 'Supply Chain', definition: 'The entire process of producing and delivering a product, from raw materials to the consumer.' },
  { term: 'Petrodollar', definition: 'The practice of pricing oil in US dollars, which supports global demand for the dollar.' },
  { term: 'Reserve Currency', definition: 'A currency held in large quantities by governments for international trade. The US dollar has been the primary reserve currency since World War II.' },
  { term: 'De-dollarization', definition: 'The global trend of reducing dependence on the US dollar for trade and reserves.' },
  { term: 'BRICS', definition: 'An economic alliance of Brazil, Russia, India, China, and South Africa — plus newer members — seeking alternatives to Western financial systems.' },
  { term: 'Sovereign Debt', definition: 'Money owed by a country\'s government. High sovereign debt can lead to credit downgrades and economic instability.' },

  // ── More Trading ──
  { term: 'Backtest', definition: 'Testing a trading strategy against historical data to see how it would have performed.' },
  { term: 'Paper Trading', definition: 'Practicing trades with fake money in a simulated market, useful for learning without risk.' },
  { term: 'Algorithmic Trading', definition: 'Using computer programs to execute trades automatically based on predefined rules and market conditions.' },
  { term: 'High-Frequency Trading (HFT)', definition: 'Ultra-fast algorithmic trading that executes thousands of trades per second, often exploiting tiny price differences.' },
  { term: 'Quant', definition: 'A quantitative analyst who uses mathematical models and data analysis to make trading decisions.' },
  { term: 'Whale Alert', definition: 'A notification service that tracks large cryptocurrency transfers, giving traders a heads-up about potential market-moving activity.' },
  { term: 'Fear Index (VIX)', definition: 'The CBOE Volatility Index — a measure of expected stock market volatility. High VIX means investors expect big swings.' },
  { term: 'Put Option', definition: 'A contract giving you the right to sell an asset at a set price. Traders buy puts when they expect prices to fall.' },
  { term: 'Call Option', definition: 'A contract giving you the right to buy an asset at a set price. Traders buy calls when they expect prices to rise.' },
  { term: 'Strike Price', definition: 'The price at which an option contract can be exercised — the pre-agreed buy or sell price.' },
  { term: 'Expiration Date', definition: 'The date an options or futures contract expires. After this date, the contract is worthless if not exercised.' },
  { term: 'In the Money', definition: 'An option that would be profitable if exercised right now.' },
  { term: 'Out of the Money', definition: 'An option that would not be profitable if exercised right now.' },
  { term: 'Premium', definition: 'The price you pay to buy an options contract.' },
  { term: 'Implied Volatility', definition: 'The market\'s forecast of how much an asset\'s price will move, reflected in option prices.' },
  { term: 'Theta Decay', definition: 'The gradual loss of an option\'s value as it approaches expiration, all else being equal.' },
]
